### ISSUE TITLE
iOS Undefined symbols for architecture arm64:

### ISSUE THREAD

**Issue by wmslei** [timer-cp/umeng_statistics#1]
Undefined symbol: _OBJC_CLASS_$_MobClick

Undefined symbol: _OBJC_CLASS_$_UMConfigure

**Comment by timer-cp** [comment]
> Undefined symbol: _OBJC_CLASS_$_MobClick
> 
> Undefined symbol: _OBJC_CLASS_$_UMConfigure

你好，iphone6真机测试成功，并且通用版本编译也是成功的，请先排查下插件包是否下载成功
<img width="657" alt="img" src="https://user-images.githubusercontent.com/51752756/106359620-d362d280-634e-11eb-8d48-92b83a1d05fb.png">

**Comment by timer-cp** [comment]
这种情况还有可能是因为添加依赖后没有把设备和ide重新连接造成。
