### ISSUE TITLE
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/cm/Documents/cm/kol-app/ylkj_kol/ios/Pods/UMCommon/UMCommon_7.2.5/UMCommon.framework and /Users/cm/Documents/cm/kol-app/ylkj_kol/ios/Pods/UMDevice/UMDevice_1.1.0/UMDevice.framework)

### ISSUE THREAD

**Issue by mickyguo** [timer-cp/umeng_statistics#2]
The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (/Users/cm/Documents/cm/kol-app/ylkj_kol/ios/Pods/UMCommon/UMCommon_7.2.5/UMCommon.framework and /Users/cm/Documents/cm/kol-app/ylkj_kol/ios/Pods/UMDevice/UMDevice_1.1.0/UMDevice.framework)

**Comment by mickyguo** [comment]
安卓没问题 ios启动报错

**Comment by taverngoal** [comment]
Please add `s.static_framework = true` to `umeng_statistics/ios/umeng_statistics.podspec`  in iOS.  solved

or in your project, add `s.static_framework = true` to `[your project path]/ios/.symlinks/plugins/umeng_statistics/ios/umeng_statistics.podspec`

**Comment by timer-cp** [comment]
这个问题应该是他添加依赖后未断开设备重新运行导致，官方插件开发有提及。
